### ISSUE TITLE
script not injected when no <body> tag is found 

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/inject-lr-script#1]
Should decide how to handle this when no `<body>` tag exists, or whether this is not something the module should handle at all.

**Comment by jessaustin** [comment]
If this should be handled anywhere, it should probably be handled in **trumpet**. I wonder whether that's something they want to handle.

**Comment by yoshuawuyts** [comment]
I think it's ok for budo / `inject-lr-script` to fail if no body tag is present.

**Comment by mattdesl** [comment]
After looking into this, I agree. I'm just going to document it as a limitation of the module.

**Comment by tomek-he-him** [comment]
Hey @mattdesl, just a heads up that HTML5 [doesn’t require](https://stackoverflow.com/questions/9797046/whats-a-valid-html5-document) a `<head>`, `<body>` or even `<html>` tag to be present. It can imply them from other tags in the document. I use this shortcut pretty often when prototyping something real quick, would be nice if budo supported these prototypes.
