### ISSUE TITLE
404 response never finishes

### ISSUE THREAD

**Issue by cvan** [mattdesl/inject-lr-script#3]
``` js
var inject = require('inject-lr-script')
var handler = require('ecstatic')(process.cwd())

http.createServer(function (req, res) {
    return handler(req, inject(res))
}).listen(8000, cb)
```

And then try to access [http://localhost:8000/yolo.html](http://localhost:8000/yolo.html).

**Comment by cvan** [comment]
I spent some time trying to rejig things, looked at [some other usages](https://github.com/chrisdickinson/browservefy/blob/master/index.js) of [response-stream](https://github.com/substack/response-stream). I was pretty unsuccessful trying.

**Comment by mattdesl** [comment]
v2 is refactored to use the same new architecture that budo@8 is using. This should probably fix this issue...
